apiVersion: v1 
kind: Pod 
metadata: 
  name: webapp
spec:
  containers:
    - name: nginx 
      image: nginx:alpine 
      ports:
      - containerPort: 80 
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: webapp-volume
  volumes:
    - name: webapp-volume 
      persistentVolumeClaim:
        claimName: webapp-pvc 
        
