apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: pv-volume-web 
spec: 
  storageClassName: local-path
  accessModes: 
    - ReadWriteMany 
  capacity: 
    storage: 100Mi 
  hostPath:
    path: /mnt/data

