apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-vol1 
  labels: 
    type: my-claim-storage
spec:
  accessModes:
    - ReadWriteOnce 
  capacity:
    storage: 1Gi
  storageClassName: local-path
  hostPath:
    path: /tmp/data